name: My Personal Academic website
description: Something here
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: false
url: http://easterneurope.github.io/basic/
baseurl: http://easterneurope.github.io/basic/
